//
//  StyleKit.m
//  Quick Coding Test
//
//  Created by Anthony Picciano on 2/2/15.
//  Copyright (c) 2015 Anthony Picciano. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKit.h"


@implementation StyleKit

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawLoadingIconWithFrame: (CGRect)frame
{

    //// Hourglass Drawing
    UIBezierPath* hourglassPath = UIBezierPath.bezierPath;
    [hourglassPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31379 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15985 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27018 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21550 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04222 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.04222 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15985 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26471 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31379 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21550 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.23015 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27018 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37595 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45416 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37630 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54212 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39641 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47998 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51615 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26348 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68686 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83924 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.22971 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73018 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78430 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95778 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95778 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83924 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73541 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68686 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.78778 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78430 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76918 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73019 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62259 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54212 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62294 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45416 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47998 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31379 * CGRectGetHeight(frame))];
    [hourglassPath closePath];
    [hourglassPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74151 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84666 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69066 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77404 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80806 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67423 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84666 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53521 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74092 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66404 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77857 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70713 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.51986 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73264 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71787 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70713 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74091 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71642 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47951 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73238 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32432 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84666 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39238 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77924 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33415 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80692 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84666 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33359 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74151 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80831 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30810 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77421 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44641 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59677 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52962 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46221 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57651 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47246 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55348 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55935 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55935 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52962 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59677 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52643 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55348 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53668 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57651 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74151 * CGRectGetHeight(frame))];
    [hourglassPath closePath];
    [hourglassPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37048 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30414 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33438 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25858 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15334 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30874 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22623 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19170 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15334 * CGRectGetHeight(frame))];
    [hourglassPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66451 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25858 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19144 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69028 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22606 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62841 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30414 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37048 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30414 * CGRectGetHeight(frame))];
    [hourglassPath closePath];
    [hourglassPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58546 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58546 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61880 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61880 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58546 * CGRectGetHeight(frame))];
    [hourglassPath closePath];
    [hourglassPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64657 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64657 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52167 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67991 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67991 * CGRectGetHeight(frame))];
    [hourglassPath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.47722 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64657 * CGRectGetHeight(frame))];
    [hourglassPath closePath];
    hourglassPath.miterLimit = 4;

    [UIColor.blackColor setFill];
    [hourglassPath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfLoadingIconWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKit drawLoadingIconWithFrame: frame];

    UIImage* imageOfLoadingIcon = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfLoadingIcon;
}

@end
