//
//  StyleKit.h
//  Quick Coding Test
//
//  Created by Anthony Picciano on 2/2/15.
//  Copyright (c) 2015 Anthony Picciano. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKit : NSObject

// Generated Images
+ (UIImage*)imageOfLoadingIconWithFrame: (CGRect)frame;

@end
